### ISSUE TITLE
helm stucks at container creating state

### ISSUE THREAD

**Issue by sonijenk** [wardviaene/kubernetes-course#14]
Hi,

I am having a issue of installing tiller pod. I have a t2.medium master ec2 instance. After following the instructions mentioned in the helm folder in helm client and tiller in server the tiller pod goes into "Container Creating" State and the tiller-deploy deployment is not working.  have used the same version of helm that is mentioned in README.md in helm folder. Any idea how to fix it? 

ubuntu@kmaster:~$ kubectl get pods -n kube-system
NAME                              READY   STATUS              RESTARTS   AGE
coredns-5c98db65d4-bfqrw          1/1     Running             0          26h
coredns-5c98db65d4-wzlzj          1/1     Running             0          26h
etcd-kmaster                      1/1     Running             0          26h
kube-apiserver-kmaster            1/1     Running             0          26h
kube-controller-manager-kmaster   1/1     Running             0          26h
kube-proxy-78646                  1/1     Running             0          26h
kube-proxy-cb4fc                  1/1     Running             0          26h
kube-proxy-xq748                  1/1     Running             0          26h
kube-scheduler-kmaster            1/1     Running             0          26h
tiller-deploy-7674c4c47c-72s7g    0/1     ContainerCreating   0          89s
weave-net-gqwl7                   2/2     Running             0          26h
weave-net-t4wjl                   2/2     Running             0          26h
weave-net-v2nbr                   2/2     Running             0          26h
ubuntu@kmaster:~$

Regards
Sonisamal

**Comment by wardviaene** [comment]
You can check with kubectl describe pod tiller-deploy-7674c4c47c-72s7g what is going on.

-Edward
