### ISSUE TITLE
Shouldn't kubernetes-course/ingress/nginx-ingress-controller.yml use a Deployment

### ISSUE THREAD

**Issue by dkirrane** [wardviaene/kubernetes-course#2]
kubernetes-course/ingress/nginx-ingress-controller.yml is using older resource type. Should it be upgraded to a Deployment?

**Comment by wardviaene** [comment]
Hi,

Indeed, deployment is now used over replication controller, and I will change this, but just not yet. Deployment is still using the beta API. For <1.8.x you have to use apps/v1beta1 and for >=1.8.x apps/v1beta2. It'll be very soon part of the stable API, so at that point I'll change it. 

For purposes of the course, a lot of people are on different versions, so better backwards compatibility is preferred for me at this point, but you can change it yourself to a deployment in your setup.

-Edward
