### ISSUE TITLE
Pod Presets are removed since v1.20

### ISSUE THREAD

**Issue by miralita** [wardviaene/kubernetes-course#24]
Here is [discussion](https://github.com/kubernetes/kubernetes/issues/93900)
And [alternative](https://github.com/redhat-cop/podpreset-webhook)

**Comment by wardviaene** [comment]
Ah, nice to see! Once I realized pod presets were removed, I added a lecture on MutatingWebhooks, so you could implement that, but that's a lot more complicated than using your alternative. Great find!
