### ISSUE TITLE
Potential security issue

### ISSUE THREAD

**Issue by JamieSlome** [wardviaene/kubernetes-course#26]
Hello 👋

I run a security community that finds and fixes vulnerabilities in OSS. A researcher (@arshadkazmi42) has found a potential issue, which I would be eager to share with you.

Could you add a `SECURITY.md` file with an e-mail address for me to send further details to? GitHub [recommends](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) a security policy to ensure issues are responsibly disclosed, and it would help direct researchers in the future.

Looking forward to hearing from you 👍

(cc @huntr-helper)

**Comment by wardviaene** [comment]
https://github.com/wardviaene/kubernetes-course/blob/master/SECURITY.md

**Comment by JamieSlome** [comment]
@wardviaene - you can find the report directly here:
https://huntr.dev/bounties/a53ae861-ac87-4fa8-87a8-c4be4be02c7b/
