### ISSUE TITLE
How to make kubeadm/kops make use of other type of containers apart from docker

### ISSUE THREAD

**Issue by vikasgubbi** [wardviaene/kubernetes-course#4]
How to make KUBEADM/KOPS make use of other type of containers apart from docker & what would be the procedure to do it.

**Comment by vikasgubbi** [comment]
Need clarification on this

Is it a support of Kubernetes Container Runtime Interface or support of different Linux container engines.Please clarify

**Comment by wardviaene** [comment]
There is support for it in Kubernetes, but not yet in kops, see this open ticket as a reference: https://github.com/kubernetes/kops/issues/433

**Comment by vikasgubbi** [comment]
Correct me if i am wrong.

Each container engine comes with its own container run-time interface.

**Comment by wardviaene** [comment]
CRI is a plugin API, see http://blog.kubernetes.io/2016/12/container-runtime-interface-cri-in-kubernetes.html for details
