### ISSUE TITLE
Licence missing

### ISSUE THREAD

**Issue by sieben** [wardviaene/kubernetes-course#9]
Hello,

Could you add a licence to your code?

Best regards

**Comment by rus4** [comment]
im sorry i do not understand what you mean?

**Comment by sieben** [comment]
I would like to use your source. Under what licence they are released?

**Comment by wardviaene** [comment]
Hi,

I added a LICENSE file

**Comment by sieben** [comment]
Thanks a lot :)

Le ven. 8 févr. 2019 à 11:52, Edward Viaene <notifications@github.com> a
écrit :
